# Do not edit this file.

# This is the main application script. To run your web server (which you
# need to do before you can see your website in a browser), you would run
# `ruby main.rb` in Terminal.

# These lines invoke a tool call Bundler to automatically `require` several
# Ruby scripts that make this Web framework work.
require 'rubygems'
require 'bundler'
# require 'erb'
# require 'uri'
# require 'em-synchrony/activerecord'
Bundler.require

require 'active_record'
require 'sqlite3'
require './config/environments'

def database_exists?
  ActiveRecord::Base.establish_connection(
    :adapter => "sqlite3",
    :database  => "db/database-starter"
  )
  ActiveRecord::Base.connection rescue ActiveRecord::NoDatabaseError ? false : true
end

if database_exists?
  require_relative "db/define_schema"
  schema_file = File.open('db/schema.rb', 'w')
  ActiveRecord::SchemaDumper.dump ActiveRecord::Base.connection, schema_file
  schema_file.close
else
  
  puts "Please run the bin/setup command again."
  puts "You might see warnings that the databases already exist. That is OK."
  puts "But if you keep seeing this message, then ask for help."
end


Dir[File.dirname(__FILE__) + '/app/models/*.rb'].each {|file| require file }
binding.pry